version: '3.7'

services:
  frontend:
    container_name: frontend
  server:
    container_name: server
  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE