version: '3.7'

services:
  client:
    image: node:16
    container_name: client
    build: ./client
    networks:
      - frontend
  server:
    container_name: server
    build: ./server
    image: node:16
    networks:
      - frontend
      - backend
  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - backend


networks:
  frontend:
  backend: