FROM node:16

# set working directory
WORKDIR /client/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /client/app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install 
RUN npm install react-scripts@5.0.0

# add app
COPY . ./

# start app
CMD ["npm", "start"]
